// <auto-generated />
namespace JobBuddy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditingAspnetUsersRolesandaddingtablescompaniesmentorsmentorDetailsMentoroffers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditingAspnetUsersRolesandaddingtablescompaniesmentorsmentorDetailsMentoroffers));
        
        string IMigrationMetadata.Id
        {
            get { return "201912281343134_Editing-AspnetUsersRoles and adding tables companies,mentors,mentorDetails,Mentor offers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
