// <auto-generated />
namespace JobBuddy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SynchronizeUserWithMentorDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SynchronizeUserWithMentorDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201912281940181_SynchronizeUserWithMentorDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
